### PR TITLE
ENH: profile utils from typhos

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

This gives pretty good outputs now and is easy to use.
```
with pcdsutils.profile.profiler_context(['my_module', 'upstream_module']):
    my_code_to_profile()
```
Partial sample output:

<details>

```
Total time: 38.3466 s
File: /cds/home/z/zlentz/pydev/pydm/application.py
Function: exec_ at line 116

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   116                                               def exec_(self):
   117                                                   """
   118                                                   Execute the QApplication.
   119                                                   """
   120         1      38346.6  38346.6    100.0          return super(PyDMApplication, self).exec_()

Total time: 18.3053 s
File: /cds/home/z/zlentz/pydev/pydm/widgets/rules.py
Function: dispatch at line 111

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   111                                               def dispatch(self, payload):
   112                                                   """
   113                                                   Callback invoked when the RulesEngine evaluate a rule and send new value
   114                                                   to the widget. This dispatcher is a bridge between the Thread and the
   115                                                   widgets.
   116
   117                                                   Parameters
   118                                                   ----------
   119                                                   payload : dict
   120                                                       The payload data including the widget for method invoking.
   121                                                   """
   122       651          0.8      0.0      0.0          try:
   123       651          1.4      0.0      0.0              widget = payload.pop('widget')
   124       651          1.4      0.0      0.0              if isinstance(widget, weakref.ref):
   125       651          0.4      0.0      0.0                  widget_ref = widget
   126       651          0.8      0.0      0.0                  widget = widget()
   127       651          0.5      0.0      0.0              if widget is None: # Widget is dead... lets unregister the ref
   128                                                           self.rules_engine.unregister(widget_ref)
   129                                                       else:
   130       651      18300.0     28.1    100.0                  widget.rule_evaluated(payload)
   131                                                   except RuntimeError as ex:
   132                                                       logger.debug("Widget reference was gone but not yet for Python.")
   133                                                   except Exception as ex:
   134                                                       logger.exception("Error at RulesDispatcher.")

Total time: 18.2915 s
File: /cds/home/z/zlentz/pydev/pydm/widgets/base.py
Function: rule_evaluated at line 239

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   239                                               @Slot(dict)
   240                                               def rule_evaluated(self, payload):
   241                                                   """
   242                                                   Callback called when a rule has a new value for a property.
   243
   244                                                   Parameters
   245                                                   ----------
   246                                                   payload : dict
   247                                                       Dictionary containing the rule name, the property to be set and the
   248                                                       new value.
   249
   250                                                   Returns
   251                                                   -------
   252                                                   None
   253                                                   """
   254       651          0.9      0.0      0.0          name = payload.get('name', '')
   255       651          0.7      0.0      0.0          prop = payload.get('property', '')
   256       651          0.6      0.0      0.0          value = payload.get('value', None)
   257
   258       651          0.9      0.0      0.0          if prop not in self.RULE_PROPERTIES:
   259                                                       logger.error('Error at Rule: %s. %s is not part of this widget properties.',
   260                                                                    name, prop)
   261                                                       return
   262
   263       651          0.8      0.0      0.0          method_name, data_type = self.RULE_PROPERTIES[prop]
   264       651          0.5      0.0      0.0          try:
   265       651          1.2      0.0      0.0              if data_type == bool and isinstance(value, str_types):
   266                                                           # We do this as we already import json and for Python:
   267                                                           # bool("False") -> True
   268                                                           val = json.loads(value.lower())
   269                                                       else:
   270       651          0.7      0.0      0.0                  val = data_type(value)
   271
   272       651          0.9      0.0      0.0              method = getattr(self, method_name)
   273       651          0.7      0.0      0.0              if callable(method):
   274       651      18283.8     28.1    100.0                  method(val)
   275                                                       else:
   276                                                           setattr(self, method_name, val)
   277
   278                                                   except:
   279                                                       logger.error('Error at Rule: %s. Could not execute method %s with '
   280                                                                    'value %s and type as %s.',
   281                                                                    name, method_name, value, data_type.__name__)

Total time: 17.9352 s
File: /cds/home/z/zlentz/pydev/pydm/widgets/embedded_display.py
Function: showEvent at line 333

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   333                                               def showEvent(self, e):
   334                                                   """
   335                                                   Show events are sent to widgets that become visible on the screen.
   336
   337                                                   Parameters
   338                                                   ----------
   339                                                   event : QShowEvent
   340                                                   """
   341       147          0.2      0.0      0.0          if self._only_load_when_shown:
   342       147      15604.8    106.2     87.0              w = self.open_file()
   343       147          0.1      0.0      0.0              if w:
   344       147       2329.3     15.8     13.0                  self.embedded_widget = w
   345       147          0.7      0.0      0.0          if self.disconnectWhenHidden:
   346                                                       self.connect()
```

</details>

## Motivation and Context

This will make it easy to profile performance in any of our applications.

## How Has This Been Tested?

Interactively only. I think it will be hard to unit test this any further than "does it run?", which might be worth adding.

## Where Has This Been Documented?

Just here

### CODE REVIEW

**Comment by klauer** [comment]
Some weird things:
1. if `bluesky` is in the module list:
```
Traceback (most recent call last):
  File "/cds/home/k/klauer/Repos/whatrecord/to_profile.py", line 29, in <module>
    with pcdsutils.profile.profiler_context(
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.0/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/cds/home/k/klauer/dev_path/pcdsutils/profile.py", line 56, in profiler_context
    setup_profiler(module_names=module_names)
  File "/cds/home/k/klauer/dev_path/pcdsutils/profile.py", line 86, in setup_profiler
    modules = get_submodules(module_name)
  File "/cds/home/k/klauer/dev_path/pcdsutils/profile.py", line 233, in get_submodules
    return import_modules(submodule_names)
  File "/cds/home/k/klauer/dev_path/pcdsutils/profile.py", line 274, in import_modules
    module_objects.append(importlib.import_module(module_name))
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.0/lib/python3.9/site-packages/bluesky/tests/test_examples.py", line 15, in <module>
    from bluesky.examples import (simple_scan, sleepy, wait_one,
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.0/lib/python3.9/site-packages/_pytest/recwarn.py", line 276, in __exit__
    fail(
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.0/lib/python3.9/site-packages/_pytest/outcomes.py", line 196, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) were emitted. The list of emitted warnings is: [].
```

2. If `sys.modules` is used as the module list as a lazy option (used for this and below), we hit an unexpected exception:

```
ValueError: cannot hash writable memoryview object
> /cds/home/k/klauer/dev_path/pcdsutils/profile.py(211)get_native_methods()
    209     for obj in module_or_cls.__dict__.values():
    210         try:
--> 211             if obj in seen:
    212                 continue
    213             seen.add(obj)
```

3. On import we may see a non-`Exception` (`BaseException`) raised as in the `dask`, `networkx` test suites via pytest:
```python
Skipped: could not import 'cupy': No module named 'cupy'
> /cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.0/lib/python3.9/site-packages/_pytest/outcomes.py(292)importorskip()
    290             if reason is None:
    291                 reason = f"could not import {modname!r}: {exc}"
--> 292             raise Skipped(reason, allow_module_level=True) from None
    293     mod = sys.modules[modname]
    294     if minversion is None:

ipdb> Skipped.mro()
[<class 'Skipped'>, <class '_pytest.outcomes.OutcomeException'>, <class 'BaseException'>, <class 'object'>]
ipdb> Exception.mro()
[<class 'Exception'>, <class 'BaseException'>, <class 'object'>]
```

4. Here are the final list of modules I had to exclude:

```python
excluding = {
    "IPython",
    "bluesky",  # test suite raises
    "cryptography",
    "dask",  # baseexception
    "networkx",  # baseexception
    "numcodecs",  # baseexception
    "pandas",  # baseexception
    "pint",  # baseexception
    "pyarrow",  # baseexception
    "scipy",  # This runs a test suite on import!
    "uncertainties",  # baseexception
    "xarray",  #baseexception
}

all_modules = list(
    sorted(
        set(
            mod
            for mod in sys.modules
            if "." not in mod and mod not in excluding and not mod.startswith("_")
        )
    )
)
```

5. I wonder if submodules with `test` in the name should be excluded by default?

6. It would be nice to have an optional minimum threshold for printing functions, but that may mean reimplementing parts of what lineprofiler does for us

**Comment by klauer** [comment]
To be clear, I'm not saying using `sys.modules` is a good idea here by any stretch, but it was more of a test of: what bugs can we catch and what modules can we profile without issue.

**Comment by klauer** [comment]
And (I think) finally, for your consideration - avoiding reimplementing line_profiler, we could just filter its output by way of a simple script/utility:

<details>

```python
import dataclasses

from typing import Optional, Generator
import pint


reg = pint.UnitRegistry()


@dataclasses.dataclass
class Function:
    total_time: pint.Quantity = 0.0 * reg.s
    name: str = ""
    file: str = ""
    source: list[str] = dataclasses.field(default_factory=list)

    def __str__(self):
        return "\n".join(self.source)


def load_results(filename: str) -> Generator[Function, None, None]:
    with open(filename, "rt") as fp:
        lines = fp.read().splitlines()

    last_func = None

    for line in lines:
        if line.startswith("Total time: "):
            if last_func is not None:
                yield last_func

            _, time = line.split(": ")
            last_func = Function(total_time=reg.Quantity(time))

        if last_func:
            if line.startswith("Function: "):
                last_func.name = line.split(" ", 1)[1]
            if line.startswith("File: "):
                last_func.file = line.split(" ", 1)[1]
            if line.startswith("Could not find file "):
                last_func.file = line.split("Could not find file ", 1)[1]
            last_func.source.append(line)


    if last_func is not None and last_func.source:
        yield last_func


def filter_results(filename: str, threshold: pint.Quantity = 1.0 * reg.s):

    def by_time(func):
        return func.total_time

    for func in sorted(load_results(filename), key=by_time):
        if func.total_time > threshold:
            print(func)


print("# vi: syntax=python")
filter_results("all_results.txt", threshold=1.0 * reg.s)
```
</details>

**Comment by ZLLentz** [comment]
All good points
I removed bluesky from the list specifically due to the pytest-on-import problem
I wasn't originally interested in seeing all module outputs but maybe this was ill-guided
I think we should probably exclude obvious testing suites
I do think it makes sense to filter/process the line profiler outputs ourselves to suit our needs

**Comment by ZLLentz** [comment]
Added output sorting on total execution time
Probably should just merge it finally

**Comment by ZLLentz** [comment]
Missed the pre-commit flake8/isort stuff somehow, need to fix

**Review by klauer — APPROVED** [review]
LGTM. Excited to use these tools!

**Review by tangkong — APPROVED** [review]
This looks good to me as well.  One tangental point is that the invocation in the PR text doesn't work, since we need a proper iterable of strings.  

it looks like Ken did some testing earlier on, and while I wasn't as thorough, I did try running it on some hutch-python stuff.  

It looks like we can't really profile through the RunEngine, though I'm not sure if people want to do this.  I don't think it's worth holding the PR up, just thought it was an interesting find.

```python
In [7]: with profiler_context(['ophyd']):
   ...:     RE(bp.scan([], sim.fast_motor1, 0, 1, 10))
   ...:


Transient Scan ID: 2     Time: 2022-05-16 17:00:26
Persistent Unique Scan ID: '824785ed-020f-4b3a-8577-117f37a44d31'
New stream: 'primary'
+-----------+------------+-------------+
|   seq_num |       time | fast_motor1 |
+-----------+------------+-------------+
|         1 | 17:00:26.4 |           0 |
|         2 | 17:00:26.4 |       0.111 |
|         3 | 17:00:26.4 |       0.222 |
|         4 | 17:00:26.4 |       0.333 |
|         5 | 17:00:26.4 |       0.444 |
|         6 | 17:00:26.4 |       0.556 |
|         7 | 17:00:26.4 |       0.667 |
|         8 | 17:00:26.4 |       0.778 |
|         9 | 17:00:26.4 |       0.889 |
|        10 | 17:00:26.4 |           1 |
+-----------+------------+-------------+
generator scan ['824785ed'] (scan num: 2)

In [8]: with profiler_context(['ophyd']):
   ...:     sim.fast_motor1.get()
   ...:
Total time: 9.2e-05 s
File: /cds/home/r/roberttk/devrepos/ophyd/ophyd/device.py
Function: get at line 1351
< ... snipped output ... > 

```

**Comment by ZLLentz** [comment]
Huh, does something about the run engine output break the printer? Or does no code get run? Very strange. It should still be possible to send it to an output file maybe?
Sorry about my messy example in the description, definitely my bad.

**Comment by ZLLentz** [comment]
One big hole here, actually: I didn't leave any methods for resetting the profiler. So when invoked as above in Robert's comment within the same session it should be accumulating values with no recourse if you want to profile only one block at a time.

**Comment by tangkong** [comment]
I was wondering about resetting the profiler, but when I ran it with other methods it seemed to reset on its own.  Does it clear its buffer automatically as part of the context manager cleanup?  I just assumed it was some line_profiler magic

**Comment by tangkong** [comment]
> Huh, does something about the run engine output break the printer? Or does no code get run? Very strange. It should still be possible to send it to an output file maybe? 

It doesn't send anything to an output file if specified.  You're also very much right about the profiler not clearing the buffer.  If I profile something properly beforehand, then try to profile the RunEngine call and output to a file, the previous profile result is printed.  (sorry if that's a poorly phrased description)

**Comment by ZLLentz** [comment]
Gotcha, I understand. I think I want to merge first to get this in, and then in a follow-up PR:
- add a dedicated "reset" function for the global profiler
- make the context manager by default not use the global profiler- create a profiler for that block and process the output all in one go

**Pull request merged**
